In [20]:
import pandas as pd

In [49]:
df = pd.read_csv(r'C:\Users\original\Downloads\FCBshop.csv')
df.head()

,product_collection,product_name,price
0,STADIUM COLLECTION,UCL Men's home jersey 24/25 FC Barcelona,"LE 7,499.00 EGP"
1,ADVANCED TECH,FC Barcelona home short 24/25 - Player's Edition,"LE 4,891.00 EGP"
2,STADIUM COLLECTION,UCL Junior home jersey 24/25 FC Barcelona,"LE 6,195.00 EGP"
3,STADIUM COLLECTION,FC Barcelona home shorts 24/25 - Junior,"LE 2,608.00 EGP"
4,ADVANCED TECH,UCL Men's third jersey 24/25 FC Barcelona - Pl...,"LE 10,760.00 EGP"

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_collection  96 non-null     object
 1   product_name        96 non-null     object
 2   price               96 non-null     object
dtypes: object(3)
memory usage: 2.4+ KB

In [54]:
df['price'] = df['price'].str.replace(',', '')
df['price'] = df['price'].str.replace('LE ', '')
df['price'] = df['price'].str.replace('EGP', '')

df.price.head(20)

0      7499.00
1      4891.00
2      6195.00
3      2608.00
4     10760.00
5      4891.00
6      2282.00
7      1630.00
8      7499.00
9      3913.00
10     5543.00
11     4891.00
12     3587.00
13     5869.00
14     1630.00
15     2934.00
16      978.00
17     2608.00
18     8151.00
19     4891.00
Name: price, dtype: object

In [56]:
df['price'] = df['price'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_collection  96 non-null     object
 1   product_name        96 non-null     object
 2   price               96 non-null     float64
dtypes: float64(1), object(2)
memory usage: 2.4+ KB

In [57]:
df.head()

,product_collection,product_name,price
0,STADIUM COLLECTION,UCL Men's home jersey 24/25 FC Barcelona,7499.0
1,ADVANCED TECH,FC Barcelona home short 24/25 - Player's Edition,4891.0
2,STADIUM COLLECTION,UCL Junior home jersey 24/25 FC Barcelona,6195.0
3,STADIUM COLLECTION,FC Barcelona home shorts 24/25 - Junior,2608.0
4,ADVANCED TECH,UCL Men's third jersey 24/25 FC Barcelona - Pl...,10760.0

In [62]:
df.product_collection.value_counts()

product_collection
STADIUM COLLECTION         56
ADVANCED TECH              21
RETRO COLLECTION            4
THE CLUB COLLECTION         4
BARÃ‡A BASICS COLLECTION     4
COLDPLAY COLLECTION         2
ESSENTIALS COLLECTION       2
CRUYFF COLLECTION           1
CLAIM COLLECTION            1
FESTIVAL COLLECTION         1
Name: count, dtype: int64

In [75]:
dup = (df.duplicated())
df[dup]

,product_collection,product_name,price
8,STADIUM COLLECTION,UCL Men's home jersey 24/25 FC Barcelona,7499.0
22,STADIUM COLLECTION,FC Barcelona home shorts 24/25 - Junior,2608.0
35,STADIUM COLLECTION,UCL Men's home jersey 24/25 FC Barcelona,7499.0
36,ADVANCED TECH,FC Barcelona home short 24/25 - Player's Edition,4891.0
37,STADIUM COLLECTION,UCL Junior home jersey 24/25 FC Barcelona,6195.0
38,STADIUM COLLECTION,FC Barcelona home shorts 24/25 - Junior,2608.0
39,ADVANCED TECH,UCL Men's third jersey 24/25 FC Barcelona - Pl...,10760.0
40,ADVANCED TECH,FC Barcelona third shorts 24/25 - Player's Edi...,4891.0
73,STADIUM COLLECTION,UCL Men's home jersey 24/25 FC Barcelona,7499.0
74,ADVANCED TECH,FC Barcelona home short 24/25 - Player's Edition,4891.0
75,STADIUM COLLECTION,UCL Junior home jersey 24/25 FC Barcelona,6195.0
76,STADIUM COLLECTION,FC Barcelona home shorts 24/25 - Junior,2608.0
77,ADVANCED TECH,UCL Men's third jersey 24/25 FC Barcelona - Pl...,10760.0
78,ADVANCED TECH,FC Barcelona third shorts 24/25 - Player's Edi...,4891.0
90,STADIUM COLLECTION,UCL Men's home jersey 24/25 FC Barcelona,7499.0
91,ADVANCED TECH,FC Barcelona home short 24/25 - Player's Edition,4891.0
92,STADIUM COLLECTION,UCL Junior home jersey 24/25 FC Barcelona,6195.0
93,STADIUM COLLECTION,FC Barcelona home shorts 24/25 - Junior,2608.0
94,ADVANCED TECH,UCL Men's third jersey 24/25 FC Barcelona - Pl...,10760.0
95,ADVANCED TECH,FC Barcelona third shorts 24/25 - Player's Edi...,4891.0

In [77]:
df.shape

(96, 3)

In [79]:
df_cleaned = df.drop_duplicates()
df_cleaned.shape

(76, 3)

In [88]:
df_cleaned['product_collection'] = df_cleaned.product_collection.str.capitalize()
df_cleaned

C:\Users\original\AppData\Local\Temp\ipykernel_18248\2681484797.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['product_collection'] = df_cleaned.product_collection.str.capitalize()

,product_collection,product_name,price
0,Stadium collection,UCL Men's home jersey 24/25 FC Barcelona,7499.0
1,Advanced tech,FC Barcelona home short 24/25 - Player's Edition,4891.0
2,Stadium collection,UCL Junior home jersey 24/25 FC Barcelona,6195.0
3,Stadium collection,FC Barcelona home shorts 24/25 - Junior,2608.0
4,Advanced tech,UCL Men's third jersey 24/25 FC Barcelona - Pl...,10760.0
...,...,...,...
85,Claim collection,Hoodie ForÃ§a BarÃ§a,4239.0
86,Essentials collection,T-shirt blue ForÃ§a BarÃ§a,1956.0
87,Essentials collection,T-shirt red ForÃ§a BarÃ§a,1956.0
88,BarÃ§a basics collection,Polo maroon BarÃ§a,2934.0
89,Festival collection,Methacrylate with grass from the last pitch at...,5217.0

In [90]:
stadium_collection = df_cleaned.loc[df_cleaned['product_collection'] == 'Stadium collection', :].sort_values('price', ascending=False)
stadium_collection.head()

,product_collection,product_name,price
27,Stadium collection,UCL Men's third jersey 24/25 FC Barcelona - Pl...,10760.0
49,Stadium collection,UWCL Women's third jersey 24/25 FC Barcelona -...,10760.0
65,Stadium collection,The Club Striped Indigo Shirt,9782.0
63,Stadium collection,The Club Solid Indigo Shirt,9782.0
66,Stadium collection,The Club White Shirt,9782.0

In [91]:
#top 10 highest priced products in the store
df_cleaned.nlargest(10, 'price')

,product_collection,product_name,price
82,BarÃ§a basics collection,MESSI | Lionel Messi Official FC Barcelona Bac...,163026.0
44,Retro collection,Messi FCB Signed and Framed Branded Capt Armband,117379.0
83,BarÃ§a basics collection,Spotify Camp Nou Seat - Model 2 - LATE DELIVERY,14998.0
4,Advanced tech,UCL Men's third jersey 24/25 FC Barcelona - Pl...,10760.0
27,Stadium collection,UCL Men's third jersey 24/25 FC Barcelona - Pl...,10760.0
49,Stadium collection,UWCL Women's third jersey 24/25 FC Barcelona -...,10760.0
63,Stadium collection,The Club Solid Indigo Shirt,9782.0
64,Advanced tech,The Club Striped Indigo Shirt,9782.0
65,Stadium collection,The Club Striped Indigo Shirt,9782.0
66,Stadium collection,The Club White Shirt,9782.0

In [97]:
df_cleaned.rename(columns={'price':'price_in_EGP'}, inplace=True)
df_cleaned

C:\Users\original\AppData\Local\Temp\ipykernel_18248\1324706855.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned.rename(columns={'price':'price_in_EGP'}, inplace=True)

,product_collection,product_name,price_in_EGP
0,Stadium collection,UCL Men's home jersey 24/25 FC Barcelona,7499.0
1,Advanced tech,FC Barcelona home short 24/25 - Player's Edition,4891.0
2,Stadium collection,UCL Junior home jersey 24/25 FC Barcelona,6195.0
3,Stadium collection,FC Barcelona home shorts 24/25 - Junior,2608.0
4,Advanced tech,UCL Men's third jersey 24/25 FC Barcelona - Pl...,10760.0
...,...,...,...
85,Claim collection,Hoodie ForÃ§a BarÃ§a,4239.0
86,Essentials collection,T-shirt blue ForÃ§a BarÃ§a,1956.0
87,Essentials collection,T-shirt red ForÃ§a BarÃ§a,1956.0
88,BarÃ§a basics collection,Polo maroon BarÃ§a,2934.0
89,Festival collection,Methacrylate with grass from the last pitch at...,5217.0

In [99]:
df_cleaned.to_csv(r'C:\Users\original\Downloads\FCBstore_cleaned.csv')